import type { NextPage } from "next";
import Head from "next/head";
import Introduction from "../components/homepage/Introduction";
import PageDivider from "../components/homepage/PageDivider";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Introduction />
      <PageDivider label={"About"} />
    </div>
  );
};

export default Home;
export { getServerSideProps } from "../lib/src/Chakra";
